-- Message catalogue.
--
-- English is the default. Set `lang = "ja"` in setup() to switch.
-- Unknown keys fall back to English, then to the key itself, so a missing
-- translation degrades instead of erroring.
local M = {}

local strings = {}

strings.en = {
  -- generic
  prefix = "leterejo: ",
  no_candidates = "No candidates",
  unknown_open_mode = "Unknown open mode: %s",

  -- errors from the CLI layer
  err_passphrase = "The password store is locked",
  err_no_unlock_command = "No unlock command is set for account `%s` (set `unlock_command`)",
  err_dns = "Could not reach %s (name lookup failed). The connection may have dropped",
  err_json = "Could not parse JSON: %s",
  err_generic = "himalaya failed to run",
  err_notmuch = "notmuch failed to run",
  err_lieer = "gmi failed to run",
  err_lieer_busy = "Another gmi is using the repository; the change is only on this machine for now",
  err_no_lieer_dir = "No lieer repository is configured for this account",

  -- envelope list
  loading = "Loading…",
  syncing = "Fetching mail…",
  count = "%d messages",
  readonly = "  [read-only]",
  empty = "  (no messages)",
  no_subject = "(no subject)",
  no_name = "(unnamed)",
  filtered_by = "filtered by “%s”",
  search_hint = "%s to change, %s to clear",
  scope_local = "from the latest %d",
  scope_index = "whole index",
  searching = "Filtering… %s",

  -- continuous list
  count_of = "%s of %s",
  count_threads = "%s of %s conversations",
  loading_more = "  loading more…",
  end_of_list = "  (end of list)",

  -- column names
  col_date = "Date",
  col_from = "From",
  col_subject = "Subject",

  -- threads
  thread_loading = "Opening the conversation…",
  thread_single = "This row is a single message",
  no_threads_here = "This list is not grouped into conversations",

  -- key list
  help_title = "Keys",
  help_none = "Nothing is bound here",

  -- message view
  reading = "Loading… %s",
  attachments_head = "── %d attachment(s) ──",
  tags_head = "tags: %s",
  headers_folded = "  … %d more headers (%s to show)",
  headers_now_folded = "Headers folded",
  headers_now_shown = "Headers expanded",
  wrap_on = "Wrapping long lines",
  wrap_off = "Not wrapping; scroll sideways",
  no_message_shown = "No message is displayed",
  source_not_found = "The original message is not in the list",

  -- attachments
  no_attachments = "This message has no attachments",
  downloading = "Downloading %d attachment(s)…",
  saved_to = "Saved %d file(s) to %s",
  saved_one = "Saved: %s",
  nothing_saved = "No attachment could be saved",
  checking_attachments = "Checking attachments…",
  pick_attachment = "Attachment to open",
  opening = "Opening… (press q / Esc / Ctrl-C to quit)",
  no_open_command = "No command configured to open this",
  not_executable = "`%s` not found. Saved to: %s",
  launch_failed = "Failed to launch",
  exit_code = "Exit code %d",
  herdr_missing = "herdr not found",
  herdr_no_pane = "Could not create a pane: %s",
  herdr_no_id = "Could not read the new pane id",
  herdr_no_reply = "Could not parse herdr's response",
  herdr_run_failed = "Could not run in the pane: %s",
  tmux_outside = "Not running inside tmux",

  -- compose
  no_draft = "No draft in progress",
  draft_saved = "Draft saved: %s",
  draft_none = "No saved drafts",
  draft_failed = "Could not write the draft: %s",
  draft_unreadable = "Could not read the draft: %s",
  draft_here_only = "Drafts are kept on this machine, not on the server",
  draft_uploading = "Filing a copy in %s on `%s`…",
  draft_uploaded = "A copy is now in %s",
  draft_upload_failed = "Could not file the draft",
  no_draft_mailbox = "No draft mailbox is set for account `%s` (set `draft_mailbox`)",
  to_empty = "To is empty",
  body_empty = "Body is empty",
  no_email_configured = "No email configured for account `%s`",
  sending = "Sending as %s…%s",
  sending_via = "Sending as %s through the `%s` account…%s",
  sent = "Sent",
  unlock_prompt = "The password store is locked. Unlock it and send?",
  unlock_yes = "Unlock and send",
  unlock_no = "Not now",
  unlocked = "Unlocked",
  unlock_failed = "Nothing was unlocked",
  draft_kept = "The draft is still here",
  bcc_note = " (Bcc: %s)",
  send_failed = "Could not send",
  discard_prompt = "Discard this draft?",
  discard_yes = "Discard",
  discard_no = "Keep writing",
  reply_fallback = "Could not read the original recipients. Replying to the sender only",
  quote_headline = "On %s, %s wrote:",
  quote_headline_noname = "On %s, the sender wrote:",

  -- operations on mail
  readonly_refused = "Account `%s` is read-only; nothing was changed",
  marked_read = "Marked as read",
  marked_unread = "Marked as unread",
  marked_flagged = "Flagged",
  marked_unflagged = "Flag removed",
  already_there = "Already in %s",
  moving = "Moving to %s…",
  moved = "Moved to %s",
  archived = "Archived",
  trashed = "Moved to the trash",
  spammed = "Reported as spam",
  sync_failed = "Could not sync with Gmail (%s). The change is here but not there yet",
  no_lieer_dir_note = "The change is only on this machine: no lieer repository is configured (set `lieer.dir`, or `lieer_dir` on the account)",
  change_reverted = "Gmail had moved on, so %s did not take. The list has been read again",
  trash_prompt = "Move to the trash: %s",
  trash_yes = "Move to the trash",
  trash_no = "Keep it",

  -- pickers
  pick_mailbox = "Tag",
  pick_tag = "Tag to put on or take off",
  is_a_view = "(a view, not a tag)",
  tag_new = "make a new one…",
  tag_prompt = "New tag: ",
  tag_added = "Tagged %s",
  tag_removed = "Took %s off",
  tag_on = "* ",
  tag_off = "  ",
  desc_tag = "Put a tag on, or take one off",
  hint_tag = "tag±",
  pick_move_target = "Move to",
  pick_account = "Account",
  pick_draft = "Draft",
  search_prompt = "Filter: ",
  filter_unread = "not read yet",
  filter_flagged = "marked with a flag",
  filter_attachment = "carries an attachment",
  filter_suspicious = "the sender shown is not the sender sent (slow: reads the tag back)",
  filter_obfuscated = "invisible characters in the sender or subject (slow)",
  filter_spam = "already marked as spam",
  filter_from_here = "everything from the sender under the cursor",
  filter_write = "write one…",
  filter_clear = "clear the filter",
  pick_filter = "Filter",
  desc_filters = "Pick a filter",
  hint_filters = "filters",

  -- key hints (kept short; they share one line)
  hint_read = "open",
  hint_reply = "reply",
  hint_forward = "fwd",
  hint_compose = "new",
  hint_account = "account",
  hint_mailbox = "tag",
  hint_search = "filter",
  hint_attachments = "attach",
  hint_seen = "seen",
  hint_flagged = "flag",
  hint_trash = "trash",
  hint_archive = "arch",
  hint_spam = "spam",
  hint_move = "move",
  hint_refresh = "reload",
  hint_drafts = "drafts",
  hint_close = "close",
  hint_headers = "headers",
  hint_back = "back",

  -- keymap descriptions
  desc_read = "Open message",
  desc_reply = "Reply",
  desc_reply_other = "Reply the other way",
  desc_forward = "Forward",
  desc_compose = "Write a new message",
  desc_account = "Switch account",
  desc_mailbox = "Switch tag",
  desc_search = "Filter",
  desc_clear_search = "Clear filter",
  desc_attachments = "Save and open attachments",
  desc_toggle_seen = "Mark read or unread",
  desc_toggle_flagged = "Add or remove the flag",
  desc_trash = "Move to the trash",
  desc_archive = "Archive",
  desc_spam = "Report as spam",
  desc_move = "Move to another tag",
  desc_refresh = "Fetch mail and reload",
  desc_expand = "Open the conversation",
  desc_collapse = "Close the conversation",
  desc_toggle_thread = "Open or close the conversation",
  desc_help = "List the keys",
  desc_close = "Close",
  desc_back = "Back to list",
  desc_toggle_headers = "Toggle headers",
  desc_toggle_wrap = "Wrap long lines, or not",
  desc_send = "Send",
  desc_save_draft = "Save the draft",
  desc_upload_draft = "File the draft on the server",
  desc_drafts = "Open a saved draft",
  desc_discard = "Discard",
}

strings.ja = {
  prefix = "leterejo: ",
  no_candidates = "候補がありません",
  unknown_open_mode = "知らない開き方です: %s",

  err_passphrase = "パスワード保管庫が施錠されています",
  err_no_unlock_command = "アカウント `%s` の解錠コマンドが設定されていません (`unlock_command`)",
  err_dns = "%s に接続できませんでした (名前を引けません)。回線が一時的に途切れた可能性があります",
  err_json = "JSON を解釈できませんでした: %s",
  err_generic = "himalaya の実行に失敗しました",
  err_notmuch = "notmuch の実行に失敗しました",
  err_lieer = "gmi の実行に失敗しました",
  err_lieer_busy = "別の gmi が同じメール木を使っています。変更はいまのところ手元だけです",
  err_no_lieer_dir = "このアカウントの lieer のメール木が設定されていません",

  loading = "読み込み中…",
  syncing = "メールを取りに行っています…",
  count = "%d 件",
  readonly = "  [読み取り専用]",
  empty = "  (メールがありません)",
  no_subject = "(件名なし)",
  no_name = "(名前なし)",
  filtered_by = "「%s」で絞り込み",
  search_hint = "%s で変更、%s で解除",
  scope_local = "直近 %d 通から",
  scope_index = "索引全体から",
  searching = "絞り込んでいます… %s",

  count_of = "%s / %s 件",
  count_threads = "%s / %s 件のやり取り",
  loading_more = "  続きを読み込んでいます…",
  end_of_list = "  (ここまで)",

  col_date = "日付",
  col_from = "差出人",
  col_subject = "件名",

  thread_loading = "やり取りを開いています…",
  thread_single = "この行は 1 通だけです",
  no_threads_here = "この一覧はやり取りごとにまとめていません",

  help_title = "キー一覧",
  help_none = "ここに割り当てられたキーはありません",

  reading = "読み込み中… %s",
  attachments_head = "── 添付 %d 件 ──",
  tags_head = "タグ: %s",
  headers_folded = "  … 他 %d 個のヘッダー (%s で表示)",
  headers_now_folded = "ヘッダーをたたみました",
  headers_now_shown = "ヘッダーをすべて表示",
  wrap_on = "長い行を折り返します",
  wrap_off = "折り返しません (横にスクロールしてください)",
  no_message_shown = "表示中のメールがありません",
  source_not_found = "元のメールが一覧に見つかりません",

  no_attachments = "このメールに添付はありません",
  downloading = "添付 %d 件を保存しています…",
  saved_to = "%d 件を %s に保存しました",
  saved_one = "保存しました: %s",
  nothing_saved = "保存できる添付がありませんでした",
  checking_attachments = "添付を確認しています…",
  pick_attachment = "開く添付",
  opening = "開いています… (終わるには q / Esc / Ctrl-C)",
  no_open_command = "開くための命令が設定されていません",
  not_executable = "`%s` が見つかりません。保存先: %s",
  launch_failed = "起動に失敗しました",
  exit_code = "終了コード %d",
  herdr_missing = "herdr が見つかりません",
  herdr_no_pane = "ペインを作れませんでした: %s",
  herdr_no_id = "ペインの id を取り出せませんでした",
  herdr_no_reply = "herdr の応答を解釈できませんでした",
  herdr_run_failed = "ペインで実行できませんでした: %s",
  tmux_outside = "tmux の中で動いていません",

  no_draft = "書きかけのメールがありません",
  draft_saved = "下書きを保存しました: %s",
  draft_none = "保存した下書きはありません",
  draft_failed = "下書きを書き出せませんでした: %s",
  draft_unreadable = "下書きを読めませんでした: %s",
  draft_here_only = "下書きはこの機械の中だけに置かれます (サーバには上がりません)",
  draft_uploading = "%s (`%s`) に控えを置いています…",
  draft_uploaded = "%s に控えを置きました",
  draft_upload_failed = "下書きを置けませんでした",
  no_draft_mailbox = "アカウント `%s` の下書き用メールボックスが設定されていません (`draft_mailbox`)",
  to_empty = "宛先 (To) が空です",
  body_empty = "本文が空です",
  no_email_configured = "アカウント `%s` の email が設定されていません",
  sending = "%s から送信しています…%s",
  sending_via = "%s として `%s` アカウント経由で送信しています…%s",
  sent = "送信しました",
  unlock_prompt = "パスワード保管庫が施錠されています。解錠して送信しますか",
  unlock_yes = "解錠して送信する",
  unlock_no = "いまはやめる",
  unlocked = "解錠しました",
  unlock_failed = "解錠できませんでした",
  draft_kept = "下書きはそのまま残っています",
  bcc_note = " (Bcc: %s)",
  send_failed = "送信できませんでした",
  discard_prompt = "書きかけのメールを破棄しますか",
  discard_yes = "破棄する",
  discard_no = "書き続ける",
  reply_fallback = "元の宛先を読めませんでした。差出人にだけ返します",
  quote_headline = "%s に %s さんは書きました:",
  quote_headline_noname = "%s に、次のように書かれていました:",

  readonly_refused = "アカウント `%s` は読み取り専用です。何も変えていません",
  marked_read = "既読にしました",
  marked_unread = "未読に戻しました",
  marked_flagged = "印を付けました",
  marked_unflagged = "印を外しました",
  already_there = "すでに %s にあります",
  moving = "%s へ移しています…",
  moved = "%s へ移しました",
  archived = "保管しました",
  trashed = "ごみ箱へ移しました",
  spammed = "迷惑メールとして報告しました",
  sync_failed = "Gmail と同期できませんでした (%s)。変更は手元にはありますが、まだ向こうには届いていません",
  no_lieer_dir_note = "変更は手元だけです。lieer のメール木が設定されていません (`lieer.dir`、またはアカウントの `lieer_dir` を設定してください)",
  change_reverted = "Gmail 側が先に変わっていたため、%s は通りませんでした。一覧を読み直しました",
  trash_prompt = "ごみ箱へ移す: %s",
  trash_yes = "ごみ箱へ移す",
  trash_no = "やめる",

  pick_mailbox = "タグ",
  pick_tag = "付け外しするタグ",
  is_a_view = "(タグではなく、見え方の定義)",
  tag_new = "新しく作る…",
  tag_prompt = "新しいタグ: ",
  tag_added = "%s を付けました",
  tag_removed = "%s を外しました",
  tag_on = "* ",
  tag_off = "  ",
  desc_tag = "タグを付ける・外す",
  hint_tag = "タグ±",
  pick_move_target = "移す先",
  pick_account = "アカウント",
  pick_draft = "下書き",
  search_prompt = "絞り込み: ",
  filter_unread = "まだ読んでいない",
  filter_flagged = "印を付けた",
  filter_attachment = "添付がある",
  filter_suspicious = "差出人の表示と実体が違う (遅い: 読み直して調べる)",
  filter_obfuscated = "差出人や件名に不可視文字がある (遅い)",
  filter_spam = "迷惑メールの印が付いている",
  filter_from_here = "カーソルの差出人から来たもの全部",
  filter_write = "自分で書く…",
  filter_clear = "絞り込みを解除する",
  pick_filter = "絞り込み",
  desc_filters = "絞り込みを選ぶ",
  hint_filters = "絞込選択",

  hint_read = "開く",
  hint_reply = "返信",
  hint_forward = "転送",
  hint_compose = "新規",
  hint_account = "アカウント",
  hint_mailbox = "タグ",
  hint_search = "絞込",
  hint_attachments = "添付",
  hint_seen = "既読",
  hint_flagged = "印",
  hint_trash = "ごみ箱",
  hint_archive = "保管",
  hint_spam = "迷惑",
  hint_move = "移動",
  hint_refresh = "更新",
  hint_drafts = "下書き",
  hint_close = "閉じる",
  hint_headers = "ヘッダー",
  hint_back = "戻る",

  desc_read = "メールを開く",
  desc_reply = "返信する",
  desc_reply_other = "もう一方のやり方で返信する",
  desc_forward = "転送する",
  desc_compose = "新しく書く",
  desc_account = "アカウントを切り替える",
  desc_mailbox = "タグを切り替える",
  desc_search = "絞り込む",
  desc_clear_search = "絞り込みを解除する",
  desc_attachments = "添付を保存して開く",
  desc_toggle_seen = "既読・未読を切り替える",
  desc_toggle_flagged = "印を付け外しする",
  desc_trash = "ごみ箱へ移す",
  desc_archive = "保管する",
  desc_spam = "迷惑メールとして報告する",
  desc_move = "別のタグへ移す",
  desc_refresh = "メールを取ってきて読み直す",
  desc_expand = "やり取りを開く",
  desc_collapse = "やり取りを閉じる",
  desc_toggle_thread = "やり取りを開く・閉じる",
  desc_help = "キー一覧を出す",
  desc_close = "閉じる",
  desc_back = "一覧に戻る",
  desc_toggle_headers = "ヘッダーの表示を切り替える",
  desc_toggle_wrap = "長い行の折り返しを切り替える",
  desc_send = "送信する",
  desc_save_draft = "下書きを保存する",
  desc_upload_draft = "下書きをサーバに置く",
  desc_drafts = "保存した下書きを開く",
  desc_discard = "破棄する",
}

-- Look up a message, formatting it when arguments are given.
function M.t(key, ...)
  local lang = require("leterejo.config").options.lang or "en"
  local table_ = strings[lang] or strings.en
  local s = table_[key] or strings.en[key] or key

  if select("#", ...) > 0 then
    local ok, formatted = pcall(string.format, s, ...)
    return ok and formatted or s
  end
  return s
end

-- Same, prefixed with the plugin name. Used for anything shown as an error.
function M.e(key, ...)
  return M.t("prefix") .. M.t(key, ...)
end

-- Expose the catalogue so users can add or override entries.
function M.extend(lang, entries)
  strings[lang] = vim.tbl_extend("force", strings[lang] or {}, entries or {})
end

return M
